timeout: 6000s

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'asia.gcr.io/$PROJECT_ID/ffmpeg-gl-transition:latest',
    '.'
  ]
  id: 'build'
options:
  machineType: E2_HIGHCPU_8
