timeout: 6000s

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'asia.gcr.io/$PROJECT_ID/ffmpeg-gl-transition:$TAG_NAME',
    '-t', 'asia.gcr.io/$PROJECT_ID/ffmpeg-gl-transition:latest',
    '.'
  ]
  id: 'build'
- name: 'asia.gcr.io/$PROJECT_ID/ffmpeg-gl-transition:latest'
  entrypoint: sh
  args:
  - -c
  - "./scripts/test.sh"
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/ffmpeg-gl-transition:$TAG_NAME']
  id: 'push-tag'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/ffmpeg-gl-transition:latest']
  id: 'push-latest'
options:
  machineType: E2_HIGHCPU_8
